# Generated by Django 5.0.6 on 2024-05-23 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_current_price_alter_bid_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='current_price',
            new_name='current_bid',
        ),
    ]
