# Generated by Django 5.0.6 on 2024-05-23 20:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_current_price_listing_current_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='Wishers',
            field=models.ManyToManyField(related_name='wishes', to=settings.AUTH_USER_MODEL),
        ),
    ]
