# Generated by Django 5.0.6 on 2024-05-26 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, upload_to='commerce/static/auctions'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
