# Generated by Django 5.0.6 on 2024-05-27 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_comment_date_alter_listing_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('CLO', 'Clothing'), ('HOM', 'Home'), ('TOY', 'Toys'), ('MIS', 'Miscellaneous')], default='MIS', max_length=3),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
